dbms/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'dbms'

urlpatterns = [
    path('aboutus/',views.about,name='aboutus'),
    path('customer/', views.customer, name='customers'),
    path('contact-us/', views.contact, name='contactus'),
    path('user/<int:id>', views.userpg),
    path('transfer/<int:id>', views.transfer),
    path('success/',views.success,name='success'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demobank/urls.py
from django.contrib import admin
from django.urls import path,include
from dbms import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('bank/',include('dbms.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dbms/models.py
from django.db import models

# Create your models here.
class CustomerDetails(models.Model):
    name = models.CharField(max_length=264, default=None)
    email= models.EmailField(default=None)
    balance= models.FloatField(default=0)

    def __str__(self):
        return str(self.pk)

class History(models.Model):
    sender = models.ForeignKey(CustomerDetails, on_delete=models.DO_NOTHING)
    reciever = models.ForeignKey(CustomerDetails, related_name='reciever' , on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    msg = models.CharField(max_length=200,default=None)

    def __str__(self):
        return self.msg

dbms/views.py
from django.shortcuts import render
from dbms.models import *


# Create your views here.
def index(request):
    return render(request,"dbms/homepage.html")

def about(request):
    return render(request,"dbms/AboutUs.html")

def contact(request):
    return render(request,"dbms/ContactUs.html")

def customer(request):
    details=CustomerDetails.objects.all()
    return render(request,"dbms/customer.html",{'detail':details})

def userpg(request,id):
    details=CustomerDetails.objects.get(id=id)
    return render(request, 'dbms/user.html', {'details':details})

def transfer(request,id):
    details = CustomerDetails.objects.get(id=id)
    return render(request, 'dbms/transfer.html', {'details': details})

def success(request):
    return render(request,"dbms/success.html")

templates/dbms/AboutUs.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
<head>
  <meta charset="utf-8">
  <link href="task_1.css" rel="stylesheet">
  <link href="{% static 'css/task_1.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <title>About Us</title>
</head>

<body>
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>DEMO
    </button>
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static 'dbms/R.png' %}" alt="example" height="60px" width="60px"></a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active my-2 mx-sm-2">
          <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}">HOME<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active my-2 mx-sm-2">
          <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:aboutus' %}">About Us<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active my-2 mx-sm-2">
          <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:contactus' %}">Contact Us<span class=" sr-only">(current)</span></a>
        </li>
        <li class="nav-item active my-2 mx-sm-2">
          <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:customers' %}">Customer</a><span class=" sr-only">(current)</span></a>
        </li>
        <form class="form-inline my-2">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit" ><a href="#">Search</a></button>
        </form>
      </ul>
    </div>
  </nav>
</div>
<h1>Our Mission</h1>
<p>...</p>
<h1>Our Vision</h1>
<p>...</p>

<footer class="page-footer font-small black">
  <div class="container">
    <div class="row">
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">
          <a class="fb-ic" href="#">
          <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <a class="tw-ic" href="#">
          <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <a class="gplus-ic" href="#">
          <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <a class="li-ic" href="#">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>

</body>
</html>

templates/dbms/ContactUs.html
<!DOCTYPE html>
 <html lang="en" dir="ltr">
{% load static %}
<head>
    <meta charset="utf-8">
    <link href="task_1.css" rel="stylesheet">
    <link href="{% static 'css/task_1.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <title>ContactUs</title>
</head>

<body>
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>DEMO
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'dbms/R.png' %}" alt="example" height="60px" width="60px"></a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}">HOME<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:aboutus' %}">About Us<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:contactus' %}">Contact Us<span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:customers' %}">Customer</a><span class=" sr-only">(current)</span></a>
                </li>
                <form class="form-inline my-2">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="#">Search</a></button>
                </form>
            </ul>
        </div>
    </nav>
</div>
<h1>Contact Us</h1>
<div class="container-fluid">
    <div class="row">
        <div class="column">
            <div class="card" style="background: none; border: none">
                <a href="#">
                    <i class="fa fa-phone fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: blue; font-weight: bold;"></i>
                    9865xxxxxx
                </a>
            </div>
        </div>
        <div class="column">
            <div class="card" style="background: none; border: none">
                <a href="#" target="_blank">
                    <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: aqua; font-weight: bold;"></i>
                    @twitter
                </a>
            </div>
        </div>
        <div class="column">
            <div class="card" style="background: none; border: none">
                <a href="#" target="_blank">
                    <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: #3b5598; font-weight: bold;"></i>
                    @facebook
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <div class="card" style="background: none; border: none">
                <a href="#" target="_blank">
                    <i class="fab fa-github fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: black; font-weight: bold;"></i>
                    @github
                </a>
            </div>
        </div>
        <div class="column">
            <div class="card" style="background: none; border: none">
                <a href="#" target="_blank">
                    <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: #0e76a8; font-weight: bold;"></i>
                    @LinkedIn
                </a>
            </div>
        </div>
        <div class="column">
            <div class="card" style="background: none; border: none">
                <a href="#" target="_blank">
                    <i class="fas fa-envelope fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: #000000; font-weight: bold;"></i>
                    demo@gmail.com
                </a>
            </div>
        </div>
    </div>
    <h3>Feel free to send your Queries</h3>

    <footer class="page-footer font-small black">
        <div class="container">
            <div class="row">
                <div class="col-md-12 py-5">
                    <div class="mb-5 flex-center">
                        <a class="fb-ic" href="#">
                            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <a class="tw-ic" href="#">
                            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <a class="gplus-ic" href="#">
                            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <a class="li-ic" href="#">
                            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
</body>
</html>

templates/dbms/success.html
<!DOCTYPE html>
 <html lang="en" dir="ltr">
{% load static %}
 <head>
     <meta charset="utf-8">
     <link href="task_1.css" rel="stylesheet">
     <link href="{% static 'css/task_1.css' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
     <title>.</title>
 </head>

<body>
<div class="jumbotron" style="align-items: center;background: none">
    <h1 style="font-size: 10vw;margin-top: 10vw">TRANSACTION<br>SUCCESSFUL</h1>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>

</body>
</html>

templates/dbms/transfer.html
<!DOCTYPE html>
 <html lang="en" dir="ltr">
{% load static %}
 <head>
   <meta charset="utf-8">
     <link href="task_1.css" rel="stylesheet">
     <link href="{% static 'css/task_1.css' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
     <title>Transfer</title>
 </head>

<body style="font-weight: bold">
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>DEMO
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'dbms/R.png' %}" alt="example" height="60px" width="60px"></a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}">HOME<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:aboutus' %}">About Us<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:contactus' %}">Contact Us<span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'dbms:customers' %}">Customer<span class=" sr-only">(current)</span></a>
                </li>
                <form class="form-inline my-2">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="#">Search</a></button>
                </form>
            </ul>
        </div>
    </nav>
</div>
<div class="container">
    <h1>Transfer From</h1>
    <table class="table table-hover">
        <form>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Customer ID:</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" value="{{details.id}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Customer Name:</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" value="{{details.name}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Customer Email:</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" value="{{details.email}}">
                </div>
            </div>
</div>
</form>
</table>
<br>
<h1>Transfer To</h1>
<table class="table table-hover">
    <form>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Customer ID</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputPassword" required="true">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Transfer Amount</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputPassword" required="true">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Message </label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputPassword" required="true">
            </div>
        </div>
    </form>
</table>
<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="{% url 'dbms:success' %}">Transfer</a></button>
</div>

<footer class="page-footer font-small black">
    <div class="container">
        <div class="row">
            <div class="col-md-12 py-5">
                <div class="mb-5 flex-center">
                    <a class="fb-ic" href="#">
                        <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                    </a>
                    <a class="tw-ic" href="#">
                        <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                    </a>
                    <a class="gplus-ic" href="#">
                        <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                    </a>
                    <a class="li-ic" href="#">
                        <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>

</body>
</html>